---
title: "Exploring drought in southern Spain"
output: 
  flexdashboard::flex_dashboard:
    vertical_layout: fill
    orientation: rows
---

```{r setup, include=FALSE}
library('flexdashboard')
```

```{r pacakges}
library('RCurl')
library('plyr')
library('dplyr')
library('lubridate')
library('SPEI')
library('ggplot2')
library('zoo')
library('plotly')
source("https://gist.githubusercontent.com/ajpelu/bb0d3617b5a026ab1de67bcf84fa577a/raw/4ca37e4d5b49275146ffb7fe9a58549a6778bf5b/hydrological_year.R%2520")
library("leaflet") 
```



```{r readData}
cadiar <-read.csv(text=getURL("https://raw.githubusercontent.com/ajpelu/qpyr_resilience/master/data_raw/meteo/Cadiar.txt"), sep='', header=T)
padul <-read.csv(text=getURL("https://raw.githubusercontent.com/ajpelu/qpyr_resilience/master/data_raw/meteo/Padul.txt"), sep='', header=T)
jerez <-read.csv(text=getURL("https://raw.githubusercontent.com/ajpelu/qpyr_resilience/master/data_raw/meteo/Jerez%20del%20Marquesado.txt"), sep='', header=T)
# ba <- read.csv(text=getURL("https://raw.githubusercontent.com/ajpelu/qpyr_resilience/master/data_raw/meteo/base_aerea_aggregated.csv"), header=T, sep=',')

ltdf <- read.csv(text=getURL("https://raw.githubusercontent.com/ajpelu/qpyr_resilience/master/data_raw/meteo/long_term_data_rediam_data.txt"), header=T, sep=';', dec=',')
```


```{r}
# Compute the spei index 
compute_spei <- function(x, rango_mensual, inicio){
  # x = dataframe 
  # rango_mensual = vector with temporal range of spei
  
  # dataframe for output 
  outdf <- data.frame()
  
  for (i in rango_mensual){ 
    # Compute spei
    my_spei <- spei(x$prec_ac - x$et0_ac, i)
    
    # Create the ts 
    ts_aux <- ts(my_spei$fitted, start=inicio,frequency=12) 
    
    # Convert to dataframe 
    tsdf <- data.frame(Y=as.matrix(ts_aux), fecha=as.Date(as.yearmon(time(ts_aux))))
    
    # Rename 
    names(tsdf) <- c('value', 'fecha')
    
    
    tsdf <- tsdf %>% 
       mutate(signo = ifelse(value >= 0, 'pos', 'neg'),
              spei = paste0('spei_', i)) 
    
    # Rbind 
    outdf <- rbind(outdf, tsdf)
    
  }
  
  outdf <- outdf %>% 
    mutate(spei_ord = plyr::mapvalues(spei,
                                      c('spei_1', 'spei_3', 'spei_6', 'spei_12', 'spei_24'),
                                      c('spei_01', 'spei_03', 'spei_06', 'spei_12', 'spei_24'))) 
    
} 
```

Short-Term Serie 
=======================================================================

Row {.tabset .tabset-fade}
-------------------------------

```{r}
# Prepare data 
# Prepare data 
ca <- cadiar %>% 
  filter(complete.cases(.)) %>% 
  mutate(date = as.Date(FECHA, format="%d-%m-%y"), 
         year = lubridate::year(date), 
         month = lubridate::month(date),
         hyear = hydro_year(date), 
         hyear_f = paste0(hyear-1,'-', hyear)) %>%
  filter(year < 2016) %>% 
  dplyr::select(date, year, month, doy = DIA, tmed = Gr07TMed, prec = Gr07Precip, et0 = Gr07ETo, hyear, hyear_f) %>% 
  # Group by year and month 
  group_by(year, month, hyear, hyear_f) %>% 
  dplyr::summarise(prec_ac = sum(prec),
                   et0_ac = sum(et0),
                   tmed_avg = mean(tmed)) 


je <- jerez %>% 
  filter(complete.cases(.)) %>% 
  mutate(date = as.Date(FECHA, format="%d-%m-%y"), 
         year = lubridate::year(date), 
         month = lubridate::month(date),
         hyear = hydro_year(date), 
         hyear_f = paste0(hyear-1,'-', hyear)) %>%
  filter(year < 2016) %>% 
  dplyr::select(date, year, month, doy = DIA, tmed = Gr06TMed, prec = Gr06Precip, et0 = Gr06ETo, hyear, hyear_f) %>% 
  # Group by year and month 
  group_by(year, month, hyear, hyear_f) %>% 
  dplyr::summarise(prec_ac = sum(prec),
            et0_ac = sum(et0),
            tmed_avg = mean(tmed)) 


pa <- padul %>% 
  filter(complete.cases(.)) %>% 
  mutate(date = as.Date(FECHA, format="%d-%m-%y"), 
         year = lubridate::year(date), 
         month = lubridate::month(date),
         hyear = hydro_year(date), 
         hyear_f = paste0(hyear-1,'-', hyear)) %>%
  filter(year < 2016) %>% 
  dplyr::select(date, year, month, doy = DIA, tmed = Gr10TMed, prec = Gr10Precip, et0 = Gr10ETo, hyear, hyear_f) %>% 
  # Group by year and month 
  group_by(year, month, hyear, hyear_f) %>% 
  dplyr::summarise(prec_ac = sum(prec),
            et0_ac = sum(et0),
            tmed_avg = mean(tmed)) 
```


### Cadiar

```{r}
# SPEI Cadiar
spei_ca <- compute_spei(ca, rango_mensual = c(1,3,6,12,24), inicio = c(2000,9))

df <- spei_ca %>%
  filter(!(spei %in% c('spei_1', 'spei_24')))
site <- 'Cadiar'

# PLOT 
ggplot(df, aes(x=fecha, y=value, fill=signo)) +  
  geom_bar(stat = "identity") + 
  scale_fill_manual(values = c("pos" = "darkblue", "neg" = "red")) + 
  facet_wrap(~spei_ord, ncol=1) +
  scale_x_date(date_breaks = "1 year", date_labels = "%Y") + 
  theme_bw() + 
  ylab('SPEI') + 
  xlab('year') + 
  theme(legend.position = "none", 
        strip.background = element_blank()) +
  ggtitle(site)
```


### Padul

```{r}
# SPEI Padul
spei_pa <- compute_spei(pa, rango_mensual = c(1,3,6,12,24), inicio = c(2000,9))

df <- spei_pa %>% 
  filter(!(spei %in% c('spei_1', 'spei_24')))
site <- 'Padul' 

# PLOT 
ggplot(df, aes(x=fecha, y=value, fill=signo)) +  
  geom_bar(stat = "identity") + 
  scale_fill_manual(values = c("pos" = "darkblue", "neg" = "red")) + 
  facet_wrap(~spei_ord, ncol=1) +
  scale_x_date(date_breaks = "1 year", date_labels = "%Y") + 
  theme_bw() + 
  ylab('SPEI') + 
  xlab('year') + 
  theme(legend.position = "none", 
        strip.background = element_blank()) +
  ggtitle(site)
```


### Jerez Marquesado

```{r}

# SPEI Jerez 
spei_je <- compute_spei(je, rango_mensual = c(1,3,6,12,24), inicio = c(2000,9))

df <- spei_je %>% 
  filter(!(spei %in% c('spei_1', 'spei_24')))
site <- 'Jerez Marquesado'

# PLOT 
ggplot(df, aes(x=fecha, y=value, fill=signo)) +  
  geom_bar(stat = "identity") + 
  scale_fill_manual(values = c("pos" = "darkblue", "neg" = "red")) + 
  facet_wrap(~spei_ord, ncol=1) +
  scale_x_date(date_breaks = "1 year", date_labels = "%Y") + 
  theme_bw() + 
  ylab('SPEI') + 
  xlab('year') + 
  theme(legend.position = "none", 
        strip.background = element_blank()) +
  ggtitle(site)
```


```{r}
mysites <- c('ca','je','pa')
all_sites <- data.frame() 

for (i in mysites){ 

  df <- get(i)
  aux <- df %>% 
    dplyr::mutate(hmonth = ifelse(month <= 8, month + 4, month -8)) %>% 
    group_by(hyear_f, hmonth) %>% 
    dplyr::summarise(prec_ac = sum(prec_ac)) %>%
    mutate(csum = cumsum(prec_ac)) %>% 
    mutate(loc = i) %>% 
    as.data.frame() 
  
  all_sites <- rbind(all_sites, aux)
}

all_sites <-  all_sites %>% 
  mutate(station= plyr::mapvalues(loc, c('ca', 'je', 'pa'), c("Cadiar", "Jerez", "Padul")))
```


### Precipitation (comparison)
```{r}
df_aux <- all_sites %>% 
  filter(!(hyear_f %in% c('2004-2005', '2011-2012')))

plot_pre_all_sites <- ggplot(df_aux, aes(x=as.factor(hmonth), y=csum)) + 
  geom_boxplot() + facet_wrap(~station) + 
  geom_smooth(aes(group=1), se=TRUE, level=0.95) + 
  geom_line(data=subset(all_sites, hyear_f == '2004-2005'),
            aes(x=as.factor(hmonth), y=csum, group=1)) +
  geom_line(data=subset(all_sites, hyear_f == '2011-2012'),
            aes(x=as.factor(hmonth), y=csum, group=1),
            colour='red') +
  theme_bw() + 
  theme(strip.background = element_rect(fill = NA, color = "black")) + 
  ylab('Precipitation (mm) acumulated') + xlab('') +
  scale_x_discrete(labels=c("1"="Sep", "2"="Oct", "3"="Nov", "4"="Dec", "5"="Jan", "6"="Feb",
                            "7"="Mar", "8"="Apr", "9"="May", "10"="Jun", "11"="Jul", "12"="Aug"))
  

ggplotly(plot_pre_all_sites)
```

### Precipitation (year)

```{r}
g <- ggplot(data=all_sites, aes(x=as.factor(hmonth), y=csum, group=hyear_f, colour=hyear_f)) + 
  geom_line() + facet_wrap(~station) + theme_bw() +
  theme(strip.background = element_rect(fill = NA, color = "black")) + 
  ylab('Precipitation (mm) acumulated') + xlab('') +
  scale_x_discrete(labels=c("1"="Sep", "2"="Oct", "3"="Nov", "4"="Dec", "5"="Jan", "6"="Feb",
                            "7"="Mar", "8"="Apr", "9"="May", "10"="Jun", "11"="Jul", "12"="Aug"))

ggplotly(g)
```


Long Term Serie 
=======================================================================


Row {.tabset .tabset-fade}
-------------------------------

```{r} 
ltdf <- ltdf %>% 
  dplyr::select(cod = INDICATIVO, VARIABLE, FECHA, VALOR) %>% 
  dplyr::mutate(fecha = as.Date(FECHA, format='%d/%m/%Y'),
         month = lubridate::month(fecha),
         hmonth = ifelse(month <= 8, month + 4, month -8), 
         hyear = hydro_year(fecha),
         hyear_f = paste0(hyear-1,'-', hyear))

```

### Precipitation acc. (1950-2015)

```{r}
# We used only the 5514 station (the most long term)
# Filter by station and prec
# Filter from 1950 
st5514 <- ltdf %>% 
  filter(VARIABLE == 'PM1') %>% 
  filter(cod == '5514') %>% 
  filter(hyear >= 1950) %>% 
  dplyr::select(fecha, month, hmonth, hyear, hyear_f, pre=VALOR)

st5514_pro <- st5514 %>% 
  group_by(hyear_f, hmonth) %>% 
  dplyr::summarise(pre = sum(pre)) %>%
  dplyr::mutate(csum = cumsum(pre)) 

cum_5514 <- st5514_pro  %>% 
  filter(!(hyear_f %in% c('2004-2005', '2011-2012'))) %>% 
  ggplot(aes(x=as.factor(hmonth), y=csum)) + 
  geom_boxplot() +  
  geom_smooth(aes(group=1), se=TRUE, level=0.95, colour='black') + 
  geom_line(data=subset(st5514_pro, hyear_f == '2004-2005'),
            aes(x=as.factor(hmonth), y=csum, group=1), colour='blue') +
  geom_line(data=subset(st5514_pro, hyear_f == '2011-2012'),
            aes(x=as.factor(hmonth), y=csum, group=1),
            colour='red') +
  theme_bw() + 
  theme(strip.background = element_rect(fill = NA, color = "black")) + 
  ylab('Precipitation (mm) acumulated') + xlab('') + 
  ggtitle('Granada Base Aerea, 1950-2015') + 
  scale_x_discrete(labels=c("1"="Sep", "2"="Oct", "3"="Nov", "4"="Dec", "5"="Jan", "6"="Feb",
                            "7"="Mar", "8"="Apr", "9"="May", "10"="Jun", "11"="Jul", "12"="Aug"))


ggplotly(cum_5514)
```



### Precipitation acc. (2000-2015)

```{r}
# Cumulated precipitation from 2000 to 2015 for 5514 station 
st5514_2000  <- ltdf %>% 
  filter(VARIABLE == 'PM1') %>% 
  filter(cod == '5514') %>% 
  filter(hyear >= 1999) %>% 
  dplyr::select(fecha, month, hmonth, hyear, hyear_f, pre=VALOR) %>% 
  group_by(hyear_f, hmonth) %>% 
  dplyr::summarise(pre = sum(pre)) %>%
  dplyr::mutate(csum = cumsum(pre)) 

cum_5514_2000 <- st5514_2000 %>% 
  filter(!(hyear_f %in% c('2004-2005', '2011-2012'))) %>% 
  ggplot(aes(x=as.factor(hmonth), y=csum)) + 
  geom_boxplot() +  
  geom_smooth(aes(group=1), se=TRUE, level=0.95, colour='black') + 
  geom_line(data=subset(st5514_2000, hyear_f == '2004-2005'),
            aes(x=as.factor(hmonth), y=csum, group=1), colour='blue') +
  geom_line(data=subset(st5514_2000, hyear_f == '2011-2012'),
            aes(x=as.factor(hmonth), y=csum, group=1),
            colour='red') +
  theme_bw() + 
  theme(strip.background = element_rect(fill = NA, color = "black")) + 
  ylab('Precipitation (mm) acumulated') +  xlab('') + 
  ggtitle('Granada Base Aerea, 2000-2015') + 
  scale_x_discrete(labels=c("1"="Sep", "2"="Oct", "3"="Nov", "4"="Dec", "5"="Jan", "6"="Feb",
                            "7"="Mar", "8"="Apr", "9"="May", "10"="Jun", "11"="Jul", "12"="Aug"))


ggplotly(cum_5514_2000)
```


### Interactive plots by year 

```{r}
ba_ip <- ggplot(data=st5514_pro, 
       aes(x=as.factor(hmonth), y=csum, group=hyear_f, colour=as.factor(hyear_f))) +
  geom_line() + 
  theme_bw() + 
  ylab('Cumulative precipitation (mm)') + 
  xlab('') + ggtitle('Granada Base Aerea, 1950-2015') + 
  theme(legend.title = element_blank()) +
  scale_x_discrete(labels=c("1"="Sep", "2"="Oct", "3"="Nov", "4"="Dec", "5"="Jan", "6"="Feb",
                            "7"="Mar", "8"="Apr", "9"="May", "10"="Jun", "11"="Jul", "12"="Aug"))

ggplotly(ba_ip)
```



```{r, SPEI, eval=FALSE, echo=FALSE} 

### TODO HACER SPEI datos Rediam 
spei_ba <- compute_spei(ba, rango_mensual = c(1,3,6,12,24), inicio = c(1951,1))

df <- spei_ba %>%
  filter(!(spei %in% c('spei_1', 'spei_3')))
site <- 'Meteorological station Granada (Base Aerea)'


ggplot(df, aes(x=fecha, y=value, fill=signo)) +  
  geom_bar(stat = "identity") + 
  scale_fill_manual(values = c("pos" = "darkblue", "neg" = "red")) + 
  facet_wrap(~spei_ord, ncol=1) +
  scale_x_date(date_breaks = "10 year", date_labels = "%Y") + 
  theme_bw() + 
  ylab('Standardised Precipitation-Evapotranspiration Index') + 
  xlab('year') + 
  theme(legend.position = "none", 
        strip.background = element_blank(),
        plot.title = element_text(size = 8)) +
  ggtitle(site)  
```



Map 
=======================================================================

```{r}
geoinfo_station <-read.csv(text=getURL("https://raw.githubusercontent.com/ajpelu/qpyr_resilience/master/data_raw/meteo/metadata_station_ria.txt"), sep=';', header=T)

m <- leaflet(geoinfo_station) %>%  
    addProviderTiles("Esri.WorldImagery", 
                   group='Satellite') %>% 
  addMarkers(~long, ~lat, popup = ~as.character(name)) 

m
```








