---
title: "Analysis resilience patterns"
author: "AJ Perez-Luque (@ajpelu)"
date: "2016 May"
output:  
  md_document:
    variant: markdown_github
---
# Exploring patterns of resilience components

```{r wd, echo=FALSE}
#---------------------------------
#machine <- 'ajpelu'
machine <- 'ajpeluLap'
di <- paste('/Users/', machine, '/Dropbox/MS/MS_QUERCUS_RESI/qpyr_resilience', sep='')
#---------------------------------
```

```{r packages, warning=FALSE, message=FALSE, echo=FALSE}
source(paste0(di,"/R/exportpdf.R")) # function to export raster levelplots maps as pdf
library("dplyr")
library("ggplot2")
library("reshape2")
library("purrr")
# library("pander")
library("knitr")
source("http://www.highstat.com/Book2/HighstatLibV6.R")
library("multcomp")
library("broom")
library("effects")
```

## Read and prepare data 

```{r}
# Read data
eviresi <- read.csv(file=paste(di, "/data/evi_resilience.csv", sep=""), header = TRUE, sep = ',')

# Prepare data
elev <- read.csv(file=paste(di, "/data/elev.csv", sep=""), header = TRUE, sep = ',')

eviresi <- eviresi %>% 
  # join elevation data
  dplyr::inner_join(elev, by='iv_malla_modi_id') %>% 
  # Add a variable for population cluster
  mutate(clu_pop = as.factor(ifelse(poblacion == 1, 'a', 
                          ifelse(poblacion %in% c(2,3,4,5), 'b', 
                                 ifelse(poblacion %in% c(6,7,8), 'c', 'out')))))

# Filter out cluster 
eviresi_f <- eviresi %>% 
  filter(clu_pop != 'out') %>%
  mutate(clu_popf = as.factor(ifelse(clu_pop == 'a', 'Camarate',
                           ifelse(clu_pop == 'b','Northern slopes', 'Southern slopes'))))

```

# Models 

## Resilience 

```{r}
variable <- 'rs'

# Model 
myformula <- as.formula(paste0(variable, " ~ elev + clu_popf + elev:clu_popf"))
mymodel <- aov(myformula, data=eviresi_f)

## Summary model 
broom::tidy(mymodel)
broom::glance(mymodel)

## Evaluate terms 
drop1(mymodel, test="Chi")

## Effects plots 
### Population 
plot(effect("clu_popf",mymodel), 
     main=paste0(variable, ' vs. Cluster population'),
     xlab='Cluster population')

### Elevation
plot(effect("elev",mymodel), 
     main=paste0(variable, ' vs. Elevation'),
     xlab='Elevation (m)')

### Both 
plot(effect("elev:clu_popf",mymodel), 
     main=paste0('Interaction plot (',variable, ')'),
     xlab='Elevation (m)')


## Multiple comparison 
tuk <- glht(mymodel, linfct = mcp(clu_popf = "Tukey"))
summary(tuk)

# Convert comparisons into letters 
df_letter <- fortify(cld(tuk)) %>%
  transmute(clu_popf = as.factor(lhs),
         tukey = letters) %>%
  mutate(variable = variable)

aux_name <- paste0('df_tuk_', variable)
assign(aux_name, df_letter)
```

## Resistence

```{r}
variable <- 'rt'

# Model 
myformula <- as.formula(paste0(variable, " ~ elev + clu_popf + elev:clu_popf"))
mymodel <- aov(myformula, data=eviresi_f)

## Summary model 
broom::tidy(mymodel)
broom::glance(mymodel)

## Evaluate terms 
drop1(mymodel, test="Chi")

## Effects plots 
### Population 
plot(effect("clu_popf",mymodel), 
     main=paste0(variable, ' vs. Cluster population'),
     xlab='Cluster population')

### Elevation
plot(effect("elev",mymodel), 
     main=paste0(variable, ' vs. Elevation'),
     xlab='Elevation (m)')

### Both 
plot(effect("elev:clu_popf",mymodel), 
     main=paste0('Interaction plot (',variable, ')'),
     xlab='Elevation (m)')


## Multiple comparison 
tuk <- glht(mymodel, linfct = mcp(clu_popf = "Tukey"))
summary(tuk)

# Convert comparisons into letters 
df_letter <- fortify(cld(tuk)) %>%
  transmute(clu_popf = as.factor(lhs),
         tukey = letters) %>%
  mutate(variable = variable)

aux_name <- paste0('df_tuk_', variable)
assign(aux_name, df_letter)
```


## Recovery

```{r}
variable <- 'rc'

# Model 
myformula <- as.formula(paste0(variable, " ~ elev + clu_popf + elev:clu_popf"))
mymodel <- aov(myformula, data=eviresi_f)

## Summary model 
broom::tidy(mymodel)
broom::glance(mymodel)

## Evaluate terms 
drop1(mymodel, test="Chi")

## Effects plots 
### Population 
plot(effect("clu_popf",mymodel), 
     main=paste0(variable, ' vs. Cluster population'),
     xlab='Cluster population')

### Elevation
plot(effect("elev",mymodel), 
     main=paste0(variable, ' vs. Elevation'),
     xlab='Elevation (m)')

### Both 
plot(effect("elev:clu_popf",mymodel), 
     main=paste0('Interaction plot (',variable, ')'),
     xlab='Elevation (m)')


## Multiple comparison 
tuk <- glht(mymodel, linfct = mcp(clu_popf = "Tukey"))
summary(tuk)

# Convert comparisons into letters 
df_letter <- fortify(cld(tuk)) %>%
  transmute(clu_popf = as.factor(lhs),
         tukey = letters) %>%
  mutate(variable = variable)

aux_name <- paste0('df_tuk_', variable)
assign(aux_name, df_letter)
```


## Relative resilience

```{r}
variable <- 'rrs'

# Model 
myformula <- as.formula(paste0(variable, " ~ elev + clu_popf + elev:clu_popf"))
mymodel <- aov(myformula, data=eviresi_f)

## Summary model 
broom::tidy(mymodel)
broom::glance(mymodel)

## Evaluate terms 
drop1(mymodel, test="Chi")

## Effects plots 
### Population 
plot(effect("clu_popf",mymodel), 
     main=paste0(variable, ' vs. Cluster population'),
     xlab='Cluster population')

### Elevation
plot(effect("elev",mymodel), 
     main=paste0(variable, ' vs. Elevation'),
     xlab='Elevation (m)')

### Both 
plot(effect("elev:clu_popf",mymodel), 
     main=paste0('Interaction plot (',variable, ')'),
     xlab='Elevation (m)')


## Multiple comparison 
tuk <- glht(mymodel, linfct = mcp(clu_popf = "Tukey"))
summary(tuk)

# Convert comparisons into letters 
df_letter <- fortify(cld(tuk)) %>%
  transmute(clu_popf = as.factor(lhs),
         tukey = letters) %>%
  mutate(variable = variable)

aux_name <- paste0('df_tuk_', variable)
assign(aux_name, df_letter)
```


```{r}
variables <- c('rs','rc','rt','rrs')
auxdf <- data.frame() 

for (i in variables){ 
aux <- eviresi_f %>% 
  dplyr::group_by(clu_popf) %>% 
  summarise_each_(funs(mean, sd, se=sd(.)/sqrt(n())), i) %>% mutate(variable=i) 

auxdf <- rbind(auxdf, aux) }

label_variable <- c('rt' = 'Resistance', 
                    'rc' = 'Recovery',
                    'rs' = 'Resilience',
                    'rrs' = 'Relative Resilience')


df_all_letters <- rbind(df_tuk_rs, df_tuk_rt, df_tuk_rc, df_tuk_rrs)

auxdf <- auxdf %>% 
  inner_join(df_all_letters, by=c('clu_popf', 'variable')) 


gpop_bar_letter <- ggplot(auxdf[auxdf$variable != 'rrs',], aes(x=clu_popf, y=mean)) + 
  geom_bar(stat='identity', fill='black', colour='black') + 
  geom_errorbar(aes(ymin=mean-sd, ymax=mean+sd), 
                width=.2, position=position_dodge(.9))  +
  facet_wrap(~variable, labeller = as_labeller(label_variable)) + 
  theme_bw() + xlab('') + ylab('') + 
  geom_text(aes(label = tukey, 
                y=(mean+1.7*sd)),
           position = position_dodge(width=0.9)) +
  theme(strip.background = element_rect(fill = "white"))

gpop_bar_letter
pdf(file=paste0(di, "/man/images/plot_resicomp_bar_tukey_by_cluster.pdf"), height = 7, width = 8)
gpop_bar_letter
dev.off()


gpop_bar_letter_rrs <- ggplot(auxdf[auxdf$variable == 'rrs',], aes(x=clu_popf, y=mean)) + 
  geom_bar(stat='identity', fill='black', colour='black') + 
  geom_errorbar(aes(ymin=mean-sd, ymax=mean+sd), 
                width=.2, position=position_dodge(.9))  +
  theme_bw() + xlab('') + ylab('Relative resilience') + 
  geom_text(aes(label = tukey, 
                y=(mean+1.7*sd)),
           position = position_dodge(width=0.9)) +
  theme(strip.background = element_rect(fill = "white"))

gpop_bar_letter_rrs
pdf(file=paste0(di, "/man/images/plot_rrs_bar_tukey_by_cluster.pdf"), height = 7, width = 8)
gpop_bar_letter_rrs
dev.off()
```
