---
title: "SPEI by stations"
author: "AJ Perez-Luque (@ajpelu)"
date: "2016 Sep"
output:  
  md_document:
    toc: true
    variant: markdown_github
--- 

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
#---------------------------------
machine <- 'ajpelu'
#machine <- 'ajpeluLap'
di <- paste('/Users/', machine, '/Dropbox/phd/phd_repos/qpyr_resilience', sep='')
#---------------------------------
```

```{r}
library('plyr')
library('dplyr')
library('lubridate')
library('SPEI')
library('ggplot2')
library('zoo')
library('plotly')
source(paste0(di, '/R/hydro_year.R'))
```


```{r}
cadiar <- read.delim(file=paste0(di, '/data_raw/meteo/Cadiar.txt'), header=T, sep='')
padul <- read.delim(file=paste0(di, '/data_raw/meteo/Padul.txt'), header=T, sep='')
jerez <- read.delim(file=paste0(di, '/data_raw/meteo/Jerez del Marquesado.txt'), header=T, sep='')
                    

# Prepare data 
ca <- cadiar %>% 
  filter(complete.cases(.)) %>% 
  mutate(date = as.Date(FECHA, format="%d-%m-%y"), 
         year = lubridate::year(date), 
         month = lubridate::month(date),
         hyear = hydro_year(date), 
         hyear_f = paste0(hyear-1,'-', hyear)) %>%
  filter(year < 2016) %>% 
  select(date, year, month, doy = DIA, tmed = Gr07TMed, prec = Gr07Precip, et0 = Gr07ETo, hyear, hyear_f) %>% 
  # Group by year and month 
  group_by(year, month, hyear, hyear_f) %>% 
  summarise(prec_ac = sum(prec),
            et0_ac = sum(et0),
            tmed_avg = mean(tmed)) 


je <- jerez %>% 
  filter(complete.cases(.)) %>% 
  mutate(date = as.Date(FECHA, format="%d-%m-%y"), 
         year = lubridate::year(date), 
         month = lubridate::month(date),
         hyear = hydro_year(date), 
         hyear_f = paste0(hyear-1,'-', hyear)) %>%
  filter(year < 2016) %>% 
  select(date, year, month, doy = DIA, tmed = Gr06TMed, prec = Gr06Precip, et0 = Gr06ETo, hyear, hyear_f) %>% 
  # Group by year and month 
  group_by(year, month, hyear, hyear_f) %>% 
  summarise(prec_ac = sum(prec),
            et0_ac = sum(et0),
            tmed_avg = mean(tmed)) 


pa <- padul %>% 
  filter(complete.cases(.)) %>% 
  mutate(date = as.Date(FECHA, format="%d-%m-%y"), 
         year = lubridate::year(date), 
         month = lubridate::month(date),
         hyear = hydro_year(date), 
         hyear_f = paste0(hyear-1,'-', hyear)) %>%
  filter(year < 2016) %>% 
  select(date, year, month, doy = DIA, tmed = Gr10TMed, prec = Gr10Precip, et0 = Gr10ETo, hyear, hyear_f) %>% 
  # Group by year and month 
  group_by(year, month, hyear, hyear_f) %>% 
  summarise(prec_ac = sum(prec),
            et0_ac = sum(et0),
            tmed_avg = mean(tmed)) 

```


```{r}
# Compute the spei index 


compute_spei <- function(x, rango_mensual, inicio){
  # x = dataframe 
  # rango_mensual = vector with temporal range of spei
  
  # dataframe for output 
  outdf <- data.frame()
  
  for (i in rango_mensual){ 
    # Compute spei
    my_spei <- spei(x$prec_ac - x$et0_ac, i)
    
    # Create the ts 
    ts_aux <- ts(my_spei$fitted, start=inicio,frequency=12) 
    
    # Convert to dataframe 
    tsdf <- data.frame(Y=as.matrix(ts_aux), fecha=as.Date(as.yearmon(time(ts_aux))))
    
    # Rename 
    names(tsdf) <- c('value', 'fecha')
    
    
    tsdf <- tsdf %>% 
       mutate(signo = ifelse(value >= 0, 'pos', 'neg'),
              spei = paste0('spei_', i)) 
    
    # Rbind 
    outdf <- rbind(outdf, tsdf)
    
  }
  
  outdf <- outdf %>% 
    mutate(spei_ord = plyr::mapvalues(spei,
                                      c('spei_1', 'spei_3', 'spei_6', 'spei_12', 'spei_24'),
                                      c('spei_01', 'spei_03', 'spei_06', 'spei_12', 'spei_24'))) 
    
} 
```

```{r}
# SPEI Cadiar
spei_ca <- compute_spei(ca, rango_mensual = c(1,3,6,12,24), inicio = c(2000,9))

df <- spei_ca
site <- 'Cadiar'

# PLOT 
ggplot(df, aes(x=fecha, y=value, fill=signo)) +  
  geom_bar(stat = "identity") + 
  scale_fill_manual(values = c("pos" = "darkblue", "neg" = "red")) + 
  facet_wrap(~spei_ord, ncol=1) +
  scale_x_date(date_breaks = "1 year", date_labels = "%Y") + 
  theme_bw() + 
  ylab('SPEI') + 
  xlab('year') + 
  theme(legend.position = "none", 
        strip.background = element_blank()) +
  ggtitle(site)
```


```{r}
# SPEI Padul
spei_pa <- compute_spei(pa, rango_mensual = c(1,3,6,12,24), inicio = c(2000,9))

df <- spei_pa
site <- 'Padul' 

# PLOT 
ggplot(df, aes(x=fecha, y=value, fill=signo)) +  
  geom_bar(stat = "identity") + 
  scale_fill_manual(values = c("pos" = "darkblue", "neg" = "red")) + 
  facet_wrap(~spei_ord, ncol=1) +
  scale_x_date(date_breaks = "1 year", date_labels = "%Y") + 
  theme_bw() + 
  ylab('SPEI') + 
  xlab('year') + 
  theme(legend.position = "none", 
        strip.background = element_blank()) +
  ggtitle(site)
```


```{r}
# SPEI Jerez 
spei_je <- compute_spei(je, rango_mensual = c(1,3,6,12,24), inicio = c(2000,9))

df <- spei_je
site <- 'Jerez Marquesado'

# PLOT 
ggplot(df, aes(x=fecha, y=value, fill=signo)) +  
  geom_bar(stat = "identity") + 
  scale_fill_manual(values = c("pos" = "darkblue", "neg" = "red")) + 
  facet_wrap(~spei_ord, ncol=1) +
  scale_x_date(date_breaks = "1 year", date_labels = "%Y") + 
  theme_bw() + 
  ylab('SPEI') + 
  xlab('year') + 
  theme(legend.position = "none", 
        strip.background = element_blank()) +
  ggtitle(site)
```

### Precipitation curves


```{r}

mysites <- c('ca','je','pa')
all_sites <- data.frame() 

for (i in mysites){ 

  df <- get(i)
  aux <- df %>% 
    mutate(hmonth = ifelse(month <= 8, month + 4, month -8)) %>% 
    group_by(hyear_f, hmonth) %>% 
    summarise(prec_ac = sum(prec_ac)) %>%
    mutate(csum = cumsum(prec_ac)) %>% 
    mutate(loc = i)
  
  all_sites <- rbind(all_sites, aux)
}

all_sites <-  all_sites %>% 
  mutate(station= plyr::mapvalues(loc, c('ca', 'je', 'pa'), c("Cadiar", "Jerez", "Padul")))

all_sites %>% 
  filter(!(hyear_f %in% c('2004-2005', '2011-2012'))) %>% 
  ggplot(aes(x=as.factor(hmonth), y=csum)) + 
  geom_boxplot() + facet_wrap(~station) + 
  geom_smooth(aes(group=1), se=TRUE, level=0.95) + 
  geom_line(data=subset(all_sites, hyear_f == '2004-2005'),
            aes(x=as.factor(hmonth), y=csum, group=1)) +
  geom_line(data=subset(all_sites, hyear_f == '2011-2012'),
            aes(x=as.factor(hmonth), y=csum, group=1),
            colour='red') +
  theme_bw() + 
  theme(strip.background = element_rect(fill = NA, color = "black")) + 
  ylab('Precipitation (mm) acumulated') + 
  xlab('months (hydrological year; 1= sep)') 






g <- ggplot(data=all_sites, aes(x=as.factor(hmonth), y=csum, group=hyear_f, colour=hyear_f)) + 
  geom_line() + facet_wrap(~station) + theme_bw() +
  theme(strip.background = element_rect(fill = NA, color = "black")) + 
  xlab('months (hydrological year; 1= sep)') +
  ylab('Precipitation (mm) acumulated') 

p <- ggplotly(g)
print(p)
```


### Long term serie
```{r}
raw <- read.csv(file=paste0(di, '/data_raw/meteo/meteo_data_base_aerea.csv'), header=T, sep=';')

raw <- raw %>% 
  select(-codigo) %>% 
  mutate(miyear = lubridate::year(fecha),
         mimonth = lubridate::month(fecha),
         hyear = hydro_year(fecha),
         hyear_f = paste0(hyear-1,'-', hyear))


# Group by month-year and summarize 
pre <- raw %>%
  filter(codigo.1 == 'PI1') %>% 
  group_by(miyear, mimonth, hyear, hyear_f) %>% 
  summarize(prec_ac = sum(valor))

tmed <- raw %>%
  filter(codigo.1 == 'TI1') %>% 
  group_by(miyear, mimonth, hyear, hyear_f) %>% 
  summarize(tmed = mean(valor))

ba <- pre %>% 
  inner_join(tmed, by=c('miyear', 'mimonth', 'hyear', 'hyear_f'))


# Compute et0 
# Latitud: 37° 8' 13'' N - Longitud: 3° 37' 53'' O 
lat_ba <- 37.13694
ba$et0_ac <-thornthwaite(ba$tmed,lat_ba)

# Export data
write.csv(ba, file=paste0(di, '/data_raw/meteo/base_aerea_aggregated.csv'), row.names = FALSE)

spei_ba <- compute_spei(ba, rango_mensual = c(6,12,24), inicio = c(1951,1))


df <- spei_ba
site <- 'Base Aerea'

# PLOT 
ggplot(df, aes(x=fecha, y=value, fill=signo)) +  
  geom_bar(stat = "identity") + 
  scale_fill_manual(values = c("pos" = "darkblue", "neg" = "red")) + 
  facet_wrap(~spei_ord, ncol=1) +
  scale_x_date(date_breaks = "10 year", date_labels = "%Y") + 
  theme_bw() + 
  ylab('SPEI') + 
  xlab('year') + 
  theme(legend.position = "none", 
        strip.background = element_blank()) +
  ggtitle(site) + 
  geom_vline(xintercept=as.numeric(as.Date("2005-01-01"))) +
  geom_vline(xintercept=as.numeric(as.Date("2005-12-31"))) 
``` 

```{r}

pre_acu <- pre %>% 
  mutate(hmonth = ifelse(mimonth <= 8, mimonth + 4, mimonth -8)) %>%
  filter(!(miyear == 1951 & hmonth >= 5)) %>% 
  mutate(hyear_corrected = hyear -1)
  

cumulate_preci <- pre_acu %>% 
  group_by(hyear_corrected, hmonth) %>% 
  summarise(prec_ac = sum(prec_ac)) %>%
  mutate(csum = cumsum(prec_ac)) 
  

cumulate_preci %>% 
  filter(!(hyear_corrected %in% c(2004, 1998))) %>% 
  ggplot(aes(x=as.factor(hmonth), y=csum)) + 
  geom_boxplot() + 
  geom_smooth(aes(group=1), se=TRUE, level=0.95) + 
  geom_line(data=subset(cumulate_preci, hyear_corrected == 2004),
            aes(x=as.factor(hmonth), y=csum, group=1)) +
  geom_line(data=subset(cumulate_preci, hyear_corrected == 1998),
            aes(x=as.factor(hmonth), y=csum, group=1),
            colour='red') +
  theme_bw() + ylab('Precipitation (mm) acumulated') + 
  xlab('months (hydrological year; 1= sep)') + 
  annotate("text", label = "2004-2005", x = 2, y = 500, size = 6, colour = "black") + 
  annotate("text", label = "1998-1999", x = 2, y = 550, size = 6, colour = "red") + 
  annotate("text", label = "mean 1950-2009", x = 3, y = 600, size = 6, colour = "blue")


  



g <- ggplot(data=cumulate_preci, 
       aes(x=as.factor(hmonth), y=csum, group=hyear_corrected, colour=as.factor(hyear_corrected))) + 
  geom_line()                    

library(plotly)

p <- ggplotly(g)
print(p)

```
